# Generated by Django 2.2.12 on 2020-04-07 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('photo', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('sum_ratings', models.IntegerField()),
                ('num_ratings', models.IntegerField()),
                ('description', models.TextField()),
                ('work_experience', models.CharField(max_length=60)),
                ('resources', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('photo', models.CharField(max_length=60)),
                ('telephone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree_id', models.IntegerField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('institution', models.CharField(max_length=60)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.Trainer')),
            ],
        ),
    ]
