# Generated by Django 2.2.12 on 2020-04-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('photo', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
