# Generated by Django 2.2.12 on 2020-04-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('speciality_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='degree',
            name='degree_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
