# Generated by Django 2.2.12 on 2020-04-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainer_speciality',
            unique_together={('trainer', 'speciality')},
        ),
    ]
