# Generated by Django 2.2.12 on 2020-04-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_auto_20200424_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='speciality_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
