# Generated by Django 2.2.12 on 2020-04-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_auto_20200407_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='trainers',
            field=models.ManyToManyField(to='prof.Trainer'),
        ),
    ]
