# Generated by Django 2.2.12 on 2020-04-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_auto_20200407_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='trainers',
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialities',
            field=models.ManyToManyField(to='prof.Speciality'),
        ),
    ]
